<link rel="stylesheet" type="text/css" href="public/backend/css/admin-user/list.css">
<script src="public/backend/js/admin-user/list.js "></script>

<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-xs-6">
                <h3 class="panel-title" style="font-size: 30px">Danh sách tài khoản</h3>
            </div>
            <div class="col col-xs-6 text-right">
                <button type="button" class="btn btn-sm btn-primary btn-create"
                        onclick="location.href='?controller=admin-user&action=add'">Create New
                </button>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-bordered table-list" id="myTable">
            <thead>
            <tr>
                <th class="col-md-2">Username</th>
                <th class="col-md-3">Email</th>
                <th class="col-md-3">Họ tên</th>
                <th class="col-md-3">Nhóm tài khoản</th>
                <th class="text-center"><em class="fa fa-cog"></em></th>
            </tr>
            </thead>
            <tbody>
            <?php
            $count = count($this->view);
            for ($i = 0; $i < $count; $i++) {
                echo '<tr>';
                echo '<td>' . $this->view[$i]['username'] . '</td>';
                echo '<td>' . $this->view[$i]['email'] . '</td>';
                echo '<td class="hidden-xs">' . $this->view[$i]['fullname'] . '</td>';
                echo '<td>' . $this->view[$i]['name'] . '</td>';
                echo '<td align="center">
            <a class="btn btn-default edit" href="' . '?controller=admin-user&action=edit&id=' . $this->view[$i]['id'] . '" ><em class="fa fa-pencil"></em></a>';
                echo '<a class="btn btn-danger delete" data-confirm="Bạn có chắc muốn xoá tài khoản này không" href="' . '?controller=admin-user&action=delete&id=' . $this->view[$i]['id'] . '"><em class="fa fa-trash"></em></a>
        </td>';
                echo '</tr>';
            }
            ?>
            </tbody>
        </table>
    </div>
</div>


