<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <!--[if IE]>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>ITShop</title>
  <!-- CSS preloader -->
  <link href="css/loader.css" rel="stylesheet">
  <!-- Bootstrap core CSS -->
  <link href="public/frontend/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="public/frontend/css/megatron-template.css" rel="stylesheet">
  <!-- CSS modules -->
  <link href="public/frontend/css/icomoon.css" rel="stylesheet">
  <link href="public/frontend/css/fontello.css" rel="stylesheet">
  <link href="public/frontend/css/flexslider.css" rel="stylesheet">
  <link href="public/frontend/css/jcarousel.css" rel="stylesheet">
  <link href="public/frontend/css/owl.carousel.css" rel="stylesheet">
  <link href="public/frontend/css/owl.theme.css" rel="stylesheet">
  <link href="public/frontend/css/cloudzoom.css" rel="stylesheet">
  <link href="public/frontend/css/sfmenu.css" rel="stylesheet">
  <link href="public/frontend/css/isotope.css" rel="stylesheet">
  <link href="public/frontend/css/smoothness/jquery-ui-1.10.3.custom.min.css" rel="stylesheet">
  <link href="public/frontend/css/jquery.fancybox.css" rel="stylesheet">
  <link href="public/frontend/css/hoverfold.css" rel="stylesheet">
  <!-- SLIDER REVOLUTION 4.x CSS SETTINGS -->
  <link rel="stylesheet" type="text/css" href="public/frontend/rs-plugin/css/settings.css" media="screen" />
  <link rel="stylesheet" type="text/css" href="public/frontend/rs-plugin/css/extralayers.css" media="screen" />
</head>
<body class="responsive">
<div class="loader">
  <div class="bubblingG"> <span id="bubblingG_1"> </span> <span id="bubblingG_2"> </span> <span id="bubblingG_3"> </span> </div>
</div>
<!-- Off Canvas Menu -->
<nav id="off-canvas-menu" >
  <div id="off-canvas-menu-title">MENU<span class="icon icon-cancel-3" id="off-canvas-menu-close"></span></div>
  <ul class="expander-list">
    <li> <span class="name"><a href="master.phtml">HOME</a></span></li>
    <li><span class="name"><a href="View/Layout/View/Layout/login.phtml">ĐĂNG NHẬP</a></span></li>
    <li> <span class="name"><span class="expander">-</span> <a href="View/Layout/device.html">THIẾT BỊ ĐIỆN TỬ</a></span>
      <ul>
        <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">ĐIỆN THOẠI DI ĐỘNG</a> </span>
          <ul>
            <li><span class="name"><a href="View/Layout/device.html">Iphone</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Ipad Pro, Ipad New</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Samsung</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Sony</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Khác</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">LAPTOP</a> </span>
          <ul>
            <li><span class="name"><a href="View/Layout/device.html">Macbook</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Chormebook</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Laptop cơ bản</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Dòng giải trí</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Dòng 2-in-1</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">MÁY TÍNH BẢNG</a> </span>
          <ul>
            <li><span class="name"><a href="View/Layout/device.html">Aplle</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Samsung</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Khác</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">MÁY ẢNH &#38; MÁY QUAY PHIM</a> </span>
          <ul>
            <li><span class="name"><a href="View/Layout/device.html">Máy ảnh siêu room</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Máy chụp lấy ngay &#38; Phụ kiện</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Máy ảnh du lịch</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Camera giám sát</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Camera xe hơi</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">THIẾT BỊ ÂM THANH</a> </span>
          <ul>
            <li><span class="name"><a href="View/Layout/device.html">Âm thanh sống &#38; Sân khấu</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Máy ghi âm</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Loa di động</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Hệ thống âm thanh ngoài trời</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">TIVI</a> </span>
          <ul>
            <li><span class="name"><a href="View/Layout/device.html">Smart TV</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Tivi LCD</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Tivi Plasma</a></span></li>
            <li><span class="name"><a href="View/Layout/device.html">Tivi QLED</a></span></li>
          </ul>
        </li>
      </ul>
    </li>
    <li> <span class="name"><span class="expander">-</span> <a href="#">PHỤ KIỆN ĐIỆN TỬ</a></span>
      <ul>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">LINH KIỆN MÁY TÍNH</a> </span>
          <ul>
            <li><span class="name"><a href="#">Card màn hình</a></span></li>
            <li><span class="name"><a href="#">Hệ thống tản nhiệt</a></span></li>
            <li><span class="name"><a href="#">Ổ đĩa quang</a></span></li>
            <li><span class="name"><a href="#">RAM máy tính</a></span></li>
            <li><span class="name"><a href="#">Nguồn máy tính</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN</a> </span>
          <ul>
            <li><span class="name"><a href="#">Đèn Flash</a></span></li>
            <li><span class="name"><a href="#">Ống kính</a></span></li>
            <li><span class="name"><a href="#">Pin</a></span></li>
            <li><span class="name"><a href="#">Thẻ nhớ</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN DI ĐỘNG</a> </span>
          <ul>
            <li><span class="name"><a href="#">Pin sạc dự phòng</a></span></li>
            <li><span class="name"><a href="#">Bộ sạc có dây</a></span></li>
            <li><span class="name"><a href="#">Sim &#38; Thẻ cào</a></span></li>
            <li><span class="name"><a href="#">Ốp lưng &#38; Bao da điện thoại</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN MÁY TÍNH</a> </span>
          <ul>
            <li><span class="name"><a href="#">Chuột</a></span></li>
            <li><span class="name"><a href="#">Công cụ đồ họa</a></span></li>
            <li><span class="name"><a href="#">Màn hình máy tính</a></span></li>
            <li><span class="name"><a href="#">Miếng lót chuột</a></span></li>
            <li><span class="name"><a href="#">Pin laptop</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN TIVI</a> </span>
          <ul>
            <li><span class="name"><a href="#">Kính 3D</a></span></li>
            <li><span class="name"><a href="#">Điều khiển từ xa</a></span></li>
            <li><span class="name"><a href="#">Máy chiếu</a></span></li>
            <li><span class="name"><a href="#">Aten TV</a></span></li>
            <li><span class="name"><a href="#">Adapter TV</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">THIẾT BỊ LƯU TRỮ</a> </span>
          <ul>
            <li><span class="name"><a href="#">Ổ cứng SSD gắn ngoài</a></span></li>
            <li><span class="name"><a href="#">Ổ cứng SSD gắn trong</a></span></li>
            <li><span class="name"><a href="#">USB</a></span></li>
          </ul>
        </li>
      </ul>
    </li>
    <li> <span class="name"><span class="expander">-</span> <a href="#">CHĂM SÓC &#38; LÀM ĐẸP</a></span>
      <ul>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">CHĂM SÓC DA MẶT</a> </span>
          <ul>
            <li><span class="name"><a href="#">Dưỡng da &#38; Serum</a></span></li>
            <li><span class="name"><a href="#">Sữa rửa mặt</a></span></li>
            <li><span class="name"><a href="#">Dưỡng môi</a></span></li>
            <li><span class="name"><a href="#">Kem chống nắng &#38; Phục hồi</a></span></li>
            <li><span class="name"><a href="#">Mặt nạ lột &#38; Hạt tẩy tế bào</a></span></li>
            <li><span class="name"><a href="#">Nước hoa hồng &#38; Xịt khoáng</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">CHĂM SÓC TÓC</a> </span>
          <ul>
            <li><span class="name"><a href="#">Dầu gội</a></span></li>
            <li><span class="name"><a href="#">Dầu xả</a></span></li>
            <li><span class="name"><a href="#">Thuốc nhuộm tóc</a></span></li>
            <li><span class="name"><a href="#">Phụ kiện cho tóc</a></span></li>
            <li><span class="name"><a href="#">Tóc giả, tóc nối &#38; Phồng tóc</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">DỤNG CỤ CHĂM SÓC SẮC ĐẸP </a></span>
          <ul>
            <li><span class="name"><a href="#">Máy duỗi tóc</a></span></li>
            <li><span class="name"><a href="#">Máy làm tóc đa năng</a></span></li>
            <li><span class="name"><a href="#">Máy sấy tóc</a></span></li>
            <li><span class="name"><a href="#">Máy massage &#38; Làm thon cơ thể</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG ĐIỂM </a> </span>
          <ul>
            <li><span class="name"><a href="#">Mắt</a></span></li>
            <li><span class="name"><a href="#">Mặt</a></span></li>
            <li><span class="name"><a href="#">Môi</a></span></li>
            <li><span class="name"><a href="#">Móng</a></span></li>
            <li><span class="name"><a href="#">Tẩy trang</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">THỰC PHẨM BỔ SUNG</a> </span>
          <ul>
            <li><span class="name"><a href="#">Trà giảm cân</a></span></li>
            <li><span class="name"><a href="#">Protein</a></span></li>
            <li><span class="name"><a href="#">Phân giải và đốt cháy mỡ</a></span></li>
            <li><span class="name"><a href="#">Kiểm soát cân nặng</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">THIẾT BỊ Y TẾ</a> </span>
          <ul>
            <li><span class="name"><a href="#">Dụng cụ sơ cứu</a></span></li>
            <li><span class="name"><a href="#">Thiết bị theo dõi sức khỏe</a></span></li>
            <li><span class="name"><a href="#">Máy xông mũi họng</a></span></li>
            <li><span class="name"><a href="#">Thuốc mỡ &#38; Kem</a></span></li>
          </ul>
        </li>
      </ul>
    </li>
    <li> <span class="name"><span class="expander">-</span> <a href="#">THỜI TRANG NỮ</a></span>
      <ul>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG PHỤC NỮ</a> </span>
          <ul>
            <li><span class="name"><a href="#">Áo khoác</a></span></li>
            <li><span class="name"><a href="#">Quần jeans</a></span></li>
            <li><span class="name"><a href="#">Áo len &#38; Áo tay dài</a></span></li>
            <li><span class="name"><a href="#">Váy</a></span></li>
            <li><span class="name"><a href="#">Quần dài &#38; Quần legging</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">TÚI XÁCH NỮ</a> </span>
          <ul>
            <li><span class="name"><a href="#">Balo</a></span></li>
            <li><span class="name"><a href="#">Túi đeo chéo &#38; Túi đeo vai</a></span></li>
            <li><span class="name"><a href="#">Ví &#38; Phụ kiện</a></span></li>
            <li><span class="name"><a href="#">Túi đeo tay</a></span></li>
            <li><span class="name"><a href="#">Ví dự tiệc</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">GIÀY NỮ</a> </span>
          <ul>
            <li><span class="name"><a href="#">Giày cao gót</a></span></li>
            <li><span class="name"><a href="#">Giày đế bằng</a></span></li>
            <li><span class="name"><a href="#">Sneakers</a></span></li>
            <li><span class="name"><a href="#">Sadal</a></span></li>
            <li><span class="name"><a href="#">Dép thời trang</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN NỮ</a> </span>
          <ul>
            <li><span class="name"><a href="#">Găng tay</a></span></li>
            <li><span class="name"><a href="#">Khăn choàng</a></span></li>
            <li><span class="name"><a href="#">Mũ thời trang</a></span></li>
            <li><span class="name"><a href="#">Thắt lưng</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG PHỤC BÉ GÁI</a> </span>
          <ul>
            <li><span class="name"><a href="#">Áo bé gái</a></span></li>
            <li><span class="name"><a href="#">Áo khoác bé gái</a></span></li>
            <li><span class="name"><a href="#">Đầm bé gái</a></span></li>
            <li><span class="name"><a href="#">Quần &#38; Váy bé gái</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN BÉ GÁI</a> </span>
          <ul>
            <li><span class="name"><a href="#">Mũ bé trai</a></span></li>
            <li><span class="name"><a href="#">Dù &#38; Áo mưa bé trai</a></span></li>
            <li><span class="name"><a href="#">Găng tay &#38; Khăn bé trai</a></span></li>
          </ul>
        </li>
      </ul>
    </li>
    <li> <span class="name"><span class="expander">-</span> <a href="#">THỜI TRANG NAM</a></span>
      <ul>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG PHỤC NAM</a> </span>
          <ul>
            <li><span class="name"><a href="#">Áo khoác</a></span></li>
            <li><span class="name"><a href="#">Áo sơ mi</a></span></li>
            <li><span class="name"><a href="#">Bộ vest</a></span></li>
            <li><span class="name"><a href="#">Quần dài</a></span></li>
            <li><span class="name"><a href="#">Quần jeans</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">GIÀY NAM</a> </span>
          <ul>
            <li><span class="name"><a href="#">Giày công sở</a></span></li>
            <li><span class="name"><a href="#">Giày lười</a></span></li>
            <li><span class="name"><a href="#">Sneakers</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">TÚI XÁCH NAM</a> </span>
          <ul>
            <li><span class="name"><a href="#">Balo</a></span></li>
            <li><span class="name"><a href="#">Túi laptop đeo vai</a></span></li>
            <li><span class="name"><a href="#">Cặp công sở</a></span></li>
            <li><span class="name"><a href="#">Túi đeo chéo</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN NAM</a> </span>
          <ul>
            <li><span class="name"><a href="#">Cà vạt &#38; Nơ</a></span></li>
            <li><span class="name"><a href="#">Găng tay</a></span></li>
            <li><span class="name"><a href="#">Khăn choàng cổ</a></span></li>
            <li><span class="name"><a href="#">Thắt lưng</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG PHỤC BÉ TRAI</a> </span>
          <ul>
            <li><span class="name"><a href="#">Áo bé trai</a></span></li>
            <li><span class="name"><a href="#">Áo khoác bé trai</a></span></li>
            <li><span class="name"><a href="#">Áo len &#38; Áo khoác bé trai</a></span></li>
            <li><span class="name"><a href="#">Quần dài &#38; Quần jeans bé trai</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN BÉ TRAI</a> </span>
          <ul>
            <li><span class="name"><a href="#">Mũ bé trai</a></span></li>
            <li><span class="name"><a href="#">Dù &#38; Áo mưa bé trai</a></span></li>
            <li><span class="name"><a href="#">Găng tay &#38; Khăn bé trai</a></span></li>
          </ul>
        </li>
      </ul>
    </li>
    <li> <span class="name"><span class="expander">-</span> <a href="#">PHỤ KIỆN THỜI TRANG</a></span>
      <ul>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">ĐỒNG HỒ NAM</a> </span>
          <ul>
            <li><span class="name"><a href="#">Đồng hồ đi chơi</a></span></li>
            <li><span class="name"><a href="#">Đồng hồ đi làm</a></span></li>
            <li><span class="name"><a href="#">Đồng hồ thể thao</a></span></li>
            <li><span class="name"><a href="#">Đồng hồ thời trang</a></span></li>
            <li><span class="name"><a href="#">Phụ kiện đồng hồ</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">ĐỒNG HỒ NỮ</a> </span>
          <ul>
            <li><span class="name"><a href="#">Đồng hồ đi chơi</a></span></li>
            <li><span class="name"><a href="#">Đồng hồ đi làm</a></span></li>
            <li><span class="name"><a href="#">Đồng hồ thể thao</a></span></li>
            <li><span class="name"><a href="#">Đồng hồ thời trang</a></span></li>
            <li><span class="name"><a href="#">Phụ kiện đồng hồ</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">KÍNH THỜI TRANG</a> </span>
          <ul>
            <li><span class="name"><a href="#">Kính thời trang nữ</a></span></li>
            <li><span class="name"><a href="#">Kính thời trang nam</a></span></li>
            <li><span class="name"><a href="#">Kính thời trang trẻ em</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">KÍNH ÁP TRÒNG</a> </span>
          <ul>
            <li><span class="name"><a href="#">Kính áp tròng không màu</a></span></li>
            <li><span class="name"><a href="#">Kính áp tròng màu</a></span></li>
            <li><span class="name"><a href="#">Thuốc nhỏ mắt</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG SỨC NỮ</a> </span>
          <ul>
            <li><span class="name"><a href="#">Trang sức cao cấp</a></span></li>
            <li><span class="name"><a href="#">Trang sức thời trang</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG SỨC NAM</a> </span>
          <ul>
            <li><span class="name"><a href="#">Trang sức cao cấp</a></span></li>
            <li><span class="name"><a href="#">Trang sức thời trang</a></span></li>
          </ul>
        </li>
      </ul>
    </li>
    <li> <span class="name"> <span class="expander">-</span> <a href="#">THỂ THAO, DU LỊCH</a> </span>
      <ul>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">VALI &#38; TÚI DU LỊCH</a> </span>
          <ul>
            <li><span class="name"><a href="#">Balo &#38; Túi laptop</a></span></li>
            <li><span class="name"><a href="#">Túi du lịch</a></span></li>
            <li><span class="name"><a href="#">Vali du lịch</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">HOẠT ĐỘNG DÃ NGOẠI</a> </span>
          <ul>
            <li><span class="name"><a href="#">Câu cá</a></span></li>
            <li><span class="name"><a href="#">Golf</a></span></li>
            <li><span class="name"><a href="#">Leo núi</a></span></li>
            <li><span class="name"><a href="#">Trượt patin</a></span></li>
            <li><span class="name"><a href="#">Xe scooter</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN</a> </span>
          <ul>
            <li><span class="name"><a href="#">Dây đai &#38; Phụ kiện</a></span></li>
            <li><span class="name"><a href="#">Bình nước thể thao</a></span></li>
            <li><span class="name"><a href="#">Phụ kiện đạp xe</a></span></li>
            <li><span class="name"><a href="#">Nẹp &#38; Hỗ trợ</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">THỂ DỤC, THỂ HÌNH</a> </span>
          <ul>
            <li><span class="name"><a href="#">Chạy bộ</a></span></li>
            <li><span class="name"><a href="#">Máy tập thể hình</a></span></li>
            <li><span class="name"><a href="#">Tạ</a></span></li>
            <li><span class="name"><a href="#">Yoga</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">ĐẤM BỐC, VÕ THUẬT</a> </span>
          <ul>
            <li><span class="name"><a href="#">Đồng phục đấm bốc</a></span></li>
            <li><span class="name"><a href="#">Găng tay đấm bốc</a></span></li>
            <li><span class="name"><a href="#">Tấm lót đấm bốc</a></span></li>
            <li><span class="name"><a href="#">Bao cát &#38; Phụ kiện</a></span></li>
          </ul>
        </li>
        <li> <span class="name"> <span class="expander">-</span> <a href="#">CÁC MÔN THỂ THAO ĐỒNG ĐỘI</a> </span>
          <ul>
            <li><span class="name"><a href="#">Bóng chày</a></span></li>
            <li><span class="name"><a href="#">Bóng chuyền</a></span></li>
            <li><span class="name"><a href="#">Bóng đá</a></span></li>
            <li><span class="name"><a href="#">Bóng rổ</a></span></li>
            <li><span class="name"><a href="#">Cầu lông</a></span></li>
          </ul>
        </li>
      </ul>
    </li>
    <li><span class="name"><a href="about.html">MY TEAM</a></span></li>
  </ul>
</nav>
<!-- //end Off Canvas Menu -->

<div id="outer">
  <div id="outer-canvas"> <!-- Navbar -->
    <header class="variant2">

      <!-- Back to top -->
      <div class="back-to-top"><span class="icon-arrow-up-4"></span></div>
      <!-- //end Back to top -->

      <!-- Live Chat -->
      <div class="live-chat">
        <div class="head"><span class="icon-left icon-bubbles "></span>Hỗ trợ trực tuyến Demo<span class="caret"></span></div>
        <div class="tab-content">
          <p>Vui lòng để lại lời nhắn để được hỗ trợ</p>
          <form role="form" id="form-chat" action="#" method="get">
            <div class="form-group">
              <input type="text" class="form-control" value="Name" onFocus="if (this.value == 'Name') {this.value=''}" onBlur="if (this.value==''){this.value='Name'}">
            </div>
            <div class="form-group">
              <input type="email" class="form-control"  value="Email" onFocus="if (this.value == 'Email') {this.value=''}" onBlur="if (this.value==''){this.value='Email'}">
            </div>
            <div class="form-group">
              <textarea class="form-control" rows="3" onFocus="if (this.value == 'Message') {this.value=''}" onBlur="if (this.value==''){this.value='Message'}">Message</textarea>
            </div>
            <button  type="submit" class="btn btn-mega"  onClick="document.getElementById('form-chat').submit()">Submit</button>
          </form>
        </div>
      </div>
      <!-- //end Live Chat -->

      <section class="navbar">
        <div class="background">
          <div class="container">
            <!-- Logo -->
            <div class="navbar-logo pull-left"> <a href="index.php"><img src="#" alt="ITCLUB"></a></div>
            <!-- //end Logo -->
            <!-- Search -->
            <form class="navbar-search form-inline hidden-xs pull-right" role="form">
              <div class="form-group">
                <button type="submit" class="button"><span class="icon-search-2"></span></button>
                <input type="text" class="form-control" value="Search" onblur="if (this.value == '') {this.value = 'Search';}" onfocus="if(this.value == 'Search') {this.value = '';}">
              </div>
              <div class="dropdown-search">
                <ul>
                  <li><a href="#"><span class="amount">12</span>search auto</a></li>
                  <li><a href="#"><span class="amount">22</span>search auto</a></li>
                  <li><a href="#"><span class="amount">2</span>search auto</a></li>
                  <li><a href="#"><span class="amount">45</span>search auto</a></li>
                  <li><a href="#"><span class="amount">11</span>search auto</a></li>
                  <li><a href="#"><span class="amount">4</span>search auto</a></li>
                </ul>
              </div>
            </form>
            <!-- //end Search -->

            <div class="clearfix visible-sm"></div>
            <!-- Secondary menu -->
            <div class="navbar-secondary-menu pull-right hidden-xs">
              <div class="btn-group compact-hidden"> <a href="View/Layout/login.phtml" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown"> Tài khoản <span class="icon icon-vcard"></span><span class="caret"></span> </a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="View/Layout/login.phtml">Tài khoản</a></li>
                  <li><a href="View/Layout/login.phtml">Danh sách đơn hàng</a></li>
                  <li><a href="View/Layout/login.phtml">Kiểm tra đơn hàng</a></li>
                  <li class="divider"></li>
                  <li><a href="View/Layout/login.phtml">Đăng nhập</a></li>
                  <li><a href="View/Layout/login.phtml">Đăng xuất</a></li>
                </ul>
              </div>
              <div class="btn-group"> <a href="View/Layout/login.phtml" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown"> <span class="icon-xcart-animate"><span class="box">2</span><span class="handle"></span></span> </a>
                <div class="dropdown-menu pull-right shoppingcart-box" role="menu"> Đã thêm gần đây
                  <ul class="list">
                    <li class="item"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="preview" src="public/frontend/images/food/products/product-01-small.jpg" alt=""></a>
                      <div class="description"> <a href="View/Layout/login.phtml">Chi tiết</a> <strong class="price">1 x $44.95</strong> </div>
                    </li>
                  </ul>
                  <div class="total">Tổng: <strong>$44.95</strong></div>
                  <a href="View/Layout/login.phtml" class="btn btn-mega">Kiểm tra giỏ hàng</a>
                  <div class="view-link"><a href="View/Layout/login.phtml">Xem giỏ hàng </a></div>
                </div>
              </div>
            </div>
            <dl class="navbar-main-menu hidden-xs">
              <dt class="item">
                <ul class="sf-menu">
                  <li><a href="index.php" class="btn-main"><span class="icon icon-home"></span></a>
                    <ul>
                      <li><a href="View/Layout/login.phtml">ĐĂNG NHẬP</a></li>
                      <li><a href="View/Layout/device.html">Thiết bị điện tử</a></li>
                      <li><a href="#">Phụ kiện điện tử</a></li>
                      <li><a href="#">Chăm sóc sức khỏe &#38; Làm đẹp</a></li>
                      <li><a href="#">Thời trang Nữ</a></li>
                      <li><a href="#">Thời trang Nam</a></li>
                      <li><a href="#">Phụ kiện thời trang</a></li>
                      <li><a href="#">Thể thao, Du lịch</a></li>
                      <li><a href="about.html">MY TEAM</a></li>
                    </ul>
                  </li>
                </ul>
              </dt>
              <dd></dd>
              <dt class="item compact-hidden"> <a href="#" class="btn-main line">Thiết bị điện tử</a> </dt>
              <dd class="item-content">
                <div class="navbar-main-submenu">
                  <div class="row wrapper">
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-01-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="View/Layout/device.html">Điện thoại di động </a></div>
                        <ul>
                          <li><a href="View/Layout/device.html">Iphone</a></li>
                          <li><a href="View/Layout/device.html">Ipad Pro, Ipad New</a></li>
                          <li><a href="View/Layout/device.html">Samsung</a></li>
                          <li><a href="View/Layout/device.html">Sony</a></li>
                          <li><a href="View/Layout/device.html">Khác</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-02-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="View/Layout/device.html">Laptop</a></div>
                        <ul>
                          <li><a href="View/Layout/device.html">Macbook</a></li>
                          <li><a href="View/Layout/device.html">Chormebook</a></li>
                          <li><a href="View/Layout/device.html">Laptop cơ bản</a></li>
                          <li><a href="View/Layout/device.html">Dòng giải trí</a></li>
                          <li><a href="View/Layout/device.html">Dòng 2-in-1</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-03-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="View/Layout/device.html">Máy tính bảng</a></div>
                        <ul>
                          <li><a href="View/Layout/device.html">Apple</a></li>
                          <li><a href="View/Layout/device.html">Samsung</a></li>
                          <li><a href="View/Layout/device.html">Khác</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class=" clearfix visible-sm"></div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-04-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="View/Layout/device.html">Máy ảnh &#38; Máy quay phim </a></div>
                        <ul>
                          <li><a href="View/Layout/device.html">Máy ảnh siêu room</a></li>
                          <li><a href="View/Layout/device.html">Máy chụp lấy ngay &#38; Phụ kiện</a></li>
                          <li><a href="View/Layout/device.html">Máy ảnh du lịch</a></li>
                          <li><a href="View/Layout/device.html">Camera giám sát</a></li>
                          <li><a href="View/Layout/device.html">Camera xe hơi</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-05-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="View/Layout/device.html">Thiết bị âm thanh</a></div>
                        <ul>
                          <li><a href="View/Layout/device.html">Âm thanh sống &#38; sân khấu</a></li>
                          <li><a href="View/Layout/device.html">Máy ghi âm</a></li>
                          <li><a href="View/Layout/device.html">Loa di động</a></li>
                          <li><a href="View/Layout/device.html">Hệ thống âm thanh ngoài trời</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-06-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="View/Layout/device.html">Tivi</a></div>
                        <ul>
                          <li><a href="View/Layout/device.html">Smart TV</a></li>
                          <li><a href="View/Layout/device.html">Tivi LCD</a></li>
                          <li><a href="View/Layout/device.html">Tivi Plasma</a></li>
                          <li><a href="View/Layout/device.html">Tivi QLED</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </dd>

              <dt class="item compact-hidden"> <a href="#" class="btn-main line">PHỤ KIỆN ĐIỆN TỬ</a> </dt>
              <dd class="item-content">
                <div class="navbar-main-submenu">
                  <div class="row wrapper">
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-01-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Linh kiện máy tính</a></div>
                        <ul>
                          <li><a href="#">Card màn hình</a></li>
                          <li><a href="#">Hệ thống tản nhiệt</a></li>
                          <li><a href="#">Ổ đĩa quang</a></li>
                          <li><a href="#">RAM máy tính</a></li>
                          <li><a href="#">Nguồn máy tính</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-02-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Phụ kiện</a></div>
                        <ul>
                          <li><a href="#">Đèn Flash</a></li>
                          <li><a href="#">Ống kính</a></li>
                          <li><a href="#">Pin</a></li>
                          <li><a href="#">Thẻ nhớ</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-03-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Phụ kiện di động</a><span class="label label-mega">-25%</span></div>
                        <ul>
                          <li><a href="#">Pin sạc dự phòng</a></li>
                          <li><a href="#">Bộ sạc có dây</a></li>
                          <li><a href="#">Sim &#38; Thẻ cào </a></li>
                          <li><a href="#">Ốp lưng &#38; Bao da điện thoại</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class=" clearfix visible-sm"></div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-04-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Phụ kiện máy tính</a></div>
                        <ul>
                          <li><a href="#">Chuột</a></li>
                          <li><a href="#">Công cụ đồ họa</a></li>
                          <li><a href="#">Màn hình máy tính</a></li>
                          <li><a href="#">Miếng lót chuột </a></li>
                          <li><a href="#">Pin Laptop </a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-05-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Phụ kiện Tivi</a></div>
                        <ul>
                          <li><a href="#">Kính 3D</a></li>
                          <li><a href="#">Điều khiển từ xa</a></li>
                          <li><a href="#">Máy chiếu</a></li>
                          <li><a href="#">Anten TV</a></li>
                          <li><a href="#">Adapter TV</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-06-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Thiết bị lưu trữ</a></div>
                        <ul>
                          <li><a href="#">Ổ cứng SSD gắn ngoài</a></li>
                          <li><a href="#">Ổ cứng SSD gắn trong</a></li>
                          <li><a href="#">USB</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </dd>

              <dt class="item compact-hidden"> <a href="#" class="btn-main line">Chăm sóc &#38; Làm đẹp</a> </dt>
              <dd class="item-content">
                <div class="navbar-main-submenu">
                  <div class="row wrapper">
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-01-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Chăm sóc da mặt</a></div>
                        <ul>
                          <li><a href="#">Dưỡng da &#38; Serum</a></li>
                          <li><a href="#">Sữa rửa mặt</a></li>
                          <li><a href="#">Dưỡng môi</a></li>
                          <li><a href="#">Kem chống nắng &#38; Phụ hồi</a></li>
                          <li><a href="#">Mặt nạ lột &#38; Hạt tẩy tế bào</a></li>
                          <li><a href="#">Nước hoa hồng &#38; Xịt khoáng</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-02-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Chăm sóc tóc</a></div>
                        <ul>
                          <li><a href="#">Dầu gội</a></li>
                          <li><a href="#">Dầu xả</a></li>
                          <li><a href="#">Thuốc nhuộm tóc</a></li>
                          <li><a href="#">Phụ kiện cho tóc</a></li>
                          <li><a href="#">Tóc giả, tóc nối &#38; Phồng tóc</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-03-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Dụng cụ chăm sóc sắc đẹp</a></div>
                        <ul>
                          <li><a href="#">Máy duỗi tóc</a></li>
                          <li><a href="#">Máy làm tóc đa năng</a></li>
                          <li><a href="#">Máy sấy tóc</a></li>
                          <li><a href="#">Máy massage &#38; Làm thon cơ thể</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class=" clearfix visible-sm"></div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-04-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Trang điểm</a><span class="label label-mega">-35%</span></div>
                        <ul>
                          <li><a href="#">Mắt</a></li>
                          <li><a href="#l">Mặt</a></li>
                          <li><a href="#">Môi</a></li>
                          <li><a href="#">Móng</a></li>
                          <li><a href="#">Tẩy trang</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-05-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Thực phẩm bổ sung</a></div>
                        <ul>
                          <li><a href="#">Trà giảm cân</a></li>
                          <li><a href="#">Protein</a></li>
                          <li><a href="#">Phân giải và đốt mỡ</a></li>
                          <li><a href="#">Kiểm soát cân nặng</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-06-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Thiết bị y tế</a></div>
                        <ul>
                          <li><a href="#">Dụng cụ sơ cứu</a></li>
                          <li><a href="#">Thiết bị theo dõi sức khỏe</a></li>
                          <li><a href="#">Máy xông mũi họng</a></li>
                          <li><a href="#">Thuốc mỡ &#38; Kem</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </dd>

              <dt class="item compact-hidden"> <a href="#" class="btn-main line">Thời trang Nữ</a> </dt>
              <dd class="item-content">
                <div class="navbar-main-submenu">
                  <div class="row wrapper">
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-01-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Trang phục Nữ</a></div>
                        <ul>
                          <li><a href="#">Áo khoác</a></li>
                          <li><a href="#">Quần jeans</a></li>
                          <li><a href="#">Áo len &#38; Áo tay dài</a></li>
                          <li><a href="#">Váy</a></li>
                          <li><a href="#">Quần dài &#38; Quần legging</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-02-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Túi xách nữ</a> <span class="label label-mega">-25%</span></div>
                        <ul>
                          <li><a href="#">Balo</a></li>
                          <li><a href="#">Túi đeo chéo &#38; Túi đeo vai</a></li>
                          <li><a href="#">Ví &#38; Phụ kiện</a></li>
                          <li><a href="#">Túi đeo tay</a></li>
                          <li><a href="#">Ví dự tiệc</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-03-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Giày nữ</a> <span class="label label-mega">-15%</span></div>
                        <ul>
                          <li><a href="#">Giày cao gót</a></li>
                          <li><a href="#">Giày đế bằng</a></li>
                          <li><a href="#">Sneakers</a></li>
                          <li><a href="#">Sadal</a></li>
                          <li><a href="#">Dép thời trang</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class=" clearfix visible-sm"></div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-04-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Phụ kiện nữ</a></div>
                        <ul>
                          <li><a href="#">Găng tay</a></li>
                          <li><a href="#">Khăn choàng</a></li>
                          <li><a href="#">Mũ thời trang</a></li>
                          <li><a href="#">Thắt lưng</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-05-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Trang phục bé gái</a></div>
                        <ul>
                          <li><a href="#">Áo bé gái</a></li>
                          <li><a href="#">Áo khoác bé gái</a></li>
                          <li><a href="#">Đầm bé gái</a></li>
                          <li><a href="#">Quần &#38; Váy bé gái</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-06-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Phụ kiện bé gái</a></div>
                        <ul>
                          <li><a href="#">Mũ bé gái</a></li>
                          <li><a href="#">Dù  &#38; Áo mưa bé gái </a></li>
                          <li><a href="#">Găng tay  &#38; Khăn bé gái</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </dd>

              <dt class="item compact-hidden"> <a href="#" class="btn-main line">Thời trang Nam</a> </dt>
              <dd class="item-content">
                <div class="navbar-main-submenu">
                  <div class="row wrapper">
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-01-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Trang phục nam</a></div>
                        <ul>
                          <li><a href="#">Áo khoác </a></li>
                          <li><a href="#">Áo sơ mi</a></li>
                          <li><a href="#">Bộ vest</a></li>
                          <li><a href="#">Quần dài</a></li>
                          <li><a href="#">Quần jeans</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-02-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Giày nam</a></div>
                        <ul>
                          <li><a href="#">Giày công sở</a></li>
                          <li><a href="#">Giày lười</a></li>
                          <li><a href="#">Sneakers</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-03-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Túi xách nam</a></div>
                        <ul>
                          <li><a href="#">Balo</a></li>
                          <li><a href="#">Túi laptop đeo vai</a></li>
                          <li><a href="#">Cặp xách công sở </a></li>
                          <li><a href="#">Túi đeo chéo </a></li>
                        </ul>
                      </div>
                    </div>
                    <div class=" clearfix visible-sm"></div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-04-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Phụ kiện nam</a></div>
                        <ul>
                          <li><a href="#">Cà vạt  &#38; Nơ </a></li>
                          <li><a href="#">Găng tay</a></li>
                          <li><a href="#">Khăn choàng cổ</a></li>
                          <li><a href="#">Thắt lưng</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-05-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Trang phục bé trai</a><span class="label label-mega">-45%</span></div>
                        <ul>
                          <li><a href="#">Áo bé trai</a></li>
                          <li><a href="#">Áo khoác bé trai</a></li>
                          <li><a href="#">Áo len &#38; Áo khoác len bé trai </a></li>
                          <li><a href="#">Quần dài  &#38; Quần jeans bé trai </a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-06-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Phụ kiện bé trai</a><span class="label label-mega">-25%</span></div>
                        <ul>
                          <li><a href="#">Mũ bé trai</a></li>
                          <li><a href="#">Dù  &#38; Áo mưa bé trai </a></li>
                          <li><a href="#">Găng tay  &#38; Khăn bé trai</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </dd>

              <dt class="item compact-hidden"> <a href="#" class="btn-main line">Phụ kiện thời trang</a> </dt>
              <dd class="item-content">
                <div class="navbar-main-submenu">
                  <div class="row wrapper">
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-01-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Đồng hồ nam</a></div>
                        <ul>
                          <li><a href="#">Đồng hồ đi chơi</a></li>
                          <li><a href="#">Đồng hồ đi làm</a></li>
                          <li><a href="#">Đồng hồ thể thao</a></li>
                          <li><a href="#">Đồng hồ thời trang</a></li>
                          <li><a href="#">Phụ kiện đồng hồ</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-02-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Đồng hồ nữ</a></div>
                        <ul>
                          <li><a href="#">Đồng hồ đi chơi</a></li>
                          <li><a href="#">Đồng hồ đi làm</a></li>
                          <li><a href="#">Đồng hồ thể thao</a></li>
                          <li><a href="#">Đồng hồ thời trang</a></li>
                          <li><a href="#">Phụ kiện đồng hồ</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-03-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Kính thời trang</a><span class="label label-mega">-15%</span></div>
                        <ul>
                          <li><a href="#">Kính thời trang nữ</a></li>
                          <li><a href="#">kính thời trang nam</a></li>
                          <li><a href="#">Kính thời trang trẻ em</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class=" clearfix visible-sm"></div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-04-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Kính áp tròng</a><span class="label label-mega">-15%</span></div>
                        <ul>
                          <li><a href="#">Kính áp tròng không màu</a></li>
                          <li><a href="#">Kính áp tròng màu</a></li>
                          <li><a href="#">Thuốc nhỏ mắt</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-05-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Trang sức nữ</a></div>
                        <ul>
                          <li><a href="#">Trang sức cao cấp</a></li>
                          <li><a href="#">Trang sức thời trang</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-06-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Trang sức nam</a></div>
                        <ul>
                          <li><a href="#">Trang sức cao cấp</a></li>
                          <li><a href="#">Trang sức thời trang</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </dd>

              <dt class="item compact-hidden"> <a href="#" class="btn-main line">Thể thao &#38; Du lịch</a> </dt>
              <dd class="item-content">
                <div class="navbar-main-submenu">
                  <div class="row wrapper">
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-01-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Vali &#38; Túi du lịch</a> <span class="label label-mega">-15%</span></div>
                        <ul>
                          <li><a href="#">Balo &#38; Túi laptop</a></li>
                          <li><a href="#">Túi du lịch</a></li>
                          <li><a href="#">Vali du lịch</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-02-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Hoạt động dã ngoại</a></div>
                        <ul>
                          <li><a href="#">Câu cá</a></li>
                          <li><a href="#">Golf</a></li>
                          <li><a href="#">Leo núi</a></li>
                          <li><a href="#">Trượt patin</a></li>
                          <li><a href="#">Xe scooter</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-03-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Phụ kiện</a></div>
                        <ul>
                          <li><a href="#">Dây đai &#38; Phụ kiện</a></li>
                          <li><a href="#">Bình nước thể thao</a></li>
                          <li><a href="#">Phụ kiện đạp xe</a></li>
                          <li><a href="#">Nẹp &#38; Hỗ trợ</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class=" clearfix visible-sm"></div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-04-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Thể dục, Thể hình</a></div>
                        <ul>
                          <li><a href="#">Chạy bộ</a></li>
                          <li><a href="#">Máy tập thể hình</a></li>
                          <li><a href="#">Tạ</a></li>
                          <li><a href="#">Yoga</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-05-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Đấm bốc, võ thuật</a></div>
                        <ul>
                          <li><a href="#">Đồng phục võ thuật</a></li>
                          <li><a href="#">Găng tay đấm bốc</a></li>
                          <li><a href="#">Tấm lót đấm bốc</a></li>
                          <li><a href="#">Bao cát &#38; Phụ kiện</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-xs-4 col-md-3 col-lg-2">
                      <div class="submenu-block submenu-block-other"> <img src="public/frontend/images/temp/category-image-06-159x96.jpg" class="img-responsive" alt="">
                        <div class="title"><a class="name" href="#">Các môn thể thao đồng đội</a></div>
                        <ul>
                          <li><a href="#">Bóng chày</a></li>
                          <li><a href="#">Bóng chuyền</a></li>
                          <li><a href="#">Bóng đá</a></li>
                          <li><a href="#">Bóng rổ</a></li>
                          <li><a href="#">Cầu lông</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </dd>
              <dt class="item"> <a href="View/Layout/login.phtml" class="btn-main line">ĐĂNG NHẬP</a> </dt>
              <dd></dd>
              <dt class="item"> <a href="about.html" class="btn-main line">MY TEAM</a> </dt>
              <dd></dd>
            </dl>
            <!-- //end Main menu -->

          </div>
        </div>
        <!-- Mobile menu -->
        <div class="container visible-xs">
          <div class="mobile-nav row">
            <div class="nav-item item-01"><a href="#" id="off-canvas-menu-toggle"><span class="icon icon-list-4"></span></a></div>
            <div class="nav-item item-02"><a href="#"><span class="icon icon-vcard"></span></a>
              <div class="tab-content">
                <ul class="menu-list">
                  <li><a href="View/Layout/login.phtml">Tài khoản</a></li>
                  <li><a href="View/Layout/login.phtml">Danh sách đơn hàng</a></li>
                  <li><a href="View/Layout/login.phtml">Kiểm tra đơn hàng</a></li>
                  <li><a href="View/Layout/login.phtml">Đăng nhập</a></li>
                  <li><a href="View/Layout/login.phtml">Đăng xuất</a></li>
                </ul>
              </div>
            </div>
            <div class="nav-item item-03"><a href="#"><span class="icon icon-search-2"></span></a>
              <div class="tab-content"> <!-- Search -->
                <form class="navbar-search form-inline" role="form">
                  <div class="form-group">
                    <button type="submit" class="button"><span class="icon-search-2"></span></button>
                    <input type="text" class="form-control" value="Search" onblur="if (this.value == '') {this.value = 'Search';}" onfocus="if(this.value == 'Search') {this.value = '';}" >
                  </div>
                </form>
                <!-- //end Search -->
              </div>
            </div>
            <div class="nav-item item-04"><a href="#"><span class="icon-xcart-white">2</span></a>
              <div class="tab-content">
                <div class="shoppingcart-box">
                  <div class="title">Đã thêm gần đây</div>
                  <ul class="list">
                    <li class="item">
                      <div class="icon-product-edit"><a class="icon icon-edit" href="#"></a></div>
                      <div class="icon-product-delete"><a class="icon icon-trash-2" href="#"></a></div>
                      <a href="View/Layout/product_default.phtml" class="preview-image"><img class="preview" src="public/frontend/images/products/product-02-small.jpg" alt=""></a>
                      <div class="description"> <a href="#">Kem</a> <strong class="price">1 x $44.95</strong> </div>
                    </li>
                    <li class="item">
                      <div class="icon-product-edit"><a class="icon icon-edit" href="#"></a></div>
                      <div class="icon-product-delete"><a class="icon icon-trash-2" href="#"></a></div>
                      <a href="View/Layout/product_default.phtml" class="preview-image"><img class="preview" src="public/frontend/images/products/product-03-small.jpg" alt=""></a>
                      <div class="description"> <a href="#">Kem</a> <strong class="price">1 x $44.95</strong> </div>
                    </li>
                  </ul>
                  <div class="total">Tổng <strong>$44.95</strong></div>
                  <a href="#" class="btn btn-mega">Kiểm tra giỏ hàng</a>
                  <div class="view-link"><a href="shopping_cart.html">Xem giỏ hàng </a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- //end Mobile menu -->
        <!-- Navbar switcher -->
        <div class="navbar-switcher-container">
          <div class="navbar-switcher"> <span class="i-inactive"><img src="public/frontend/images/icon-megatron.png" width="35" height="35" alt=""></span> <span class="i-active icon-cancel-3"></span> </div>
        </div>
        <!-- //end Navbar switcher -->

      </section>

      <!-- Navbar height -->
      <div class="navbar-height-inner"></div>
      <!-- Navbar height -->

      <!-- Navbar height -->
      <div class="navbar-height"></div>
      <!-- Navbar height -->

    </header>
    <!-- //end Navbar -->

    <!-- Slider -->

    <section class="main-slider container hidden-xs">
      <div class="owl-slider-outer"> <a class="owl-slider-prev"></a> <a class="owl-slider-next"></a>
        <div class="owl-slider">
          <div class="item"><img src="public/frontend/images/home_boxed_slider1.jpg" alt=""> <a href="master.phtml" class="title-slide-01"> <span class="big">Giảm giá</span> <span class="middle">đến 40% các mặt hàng</span> </a></div>
          <div class="item"><img src="public/frontend/images/home_boxed_slider2.jpg" alt=""> <a href="master.phtml" class="title-slide-02"> <span class="big">New</span> <span class="small">Chọn</span> <span class="middle">ITCLUB</span> </a> </div>
          <div class="item"><img src="public/frontend/images/home_boxed_slider3.jpg" alt=""> <a href="master.phtml" class="title-slide-03"> <span class="big">Offer</span> <span class="middle"> SALE</span> </a></div>
        </div>
      </div>
      <div class="banners-block">
        <div class="item"><a href="#"><img src="public/frontend/images/banner1.jpg"  alt="">
          <div class="banner-text black"> 100%<br>
            IICLUB</div>
        </a></div>
        <div class="item"><a href="#"><img src="public/frontend/images/banner2.jpg"  alt="">
          <div class="banner-text">
            <div class="inside">ITCLUB<br>
              ITCLUB</div>
          </div>
        </a></div>
      </div>
    </section>

    <!-- //end Slider -->
    <!-- Services -->
    <section class="services-block hidden-xs">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-4 col-lg-4 divider-right text-center">
            <div class="icon-circle  active animate scale"><span style="display: block;" class="icon icon-airplane-2"></span> </div>
            <p><strong>GIAO HÀNG MIỄN PHÍ</strong></p><p>với đơn hàng trên $200 </p>
          </div>
          <div class="col-xs-12 col-sm-4 col-lg-4 divider-right text-center">
            <div class="icon-circle  active animate scale"><span style="display: block;" class="icon icon-clock"></span></div>
            <p><strong>ĐỔI TRẢ 30 NGÀY</strong></p><p>với các thiết bị điện tử</p>
          </div>
          <div class="col-xs-12 col-sm-4 col-lg-4 divider-right text-center">
            <div class="icon-circle  active animate scale"><span style="display: block;" class="icon icon-money-bag"></span></div>
            <p><strong>THANH TOÁN KHI GIAO HÀNG</strong></p><p>vận chuyển tận nhà</p>
          </div>
        </div>
      </div>
    </section>
    <!-- //end Services -->
    <div class="line-divider divider-xxs"></div>    <!-- Brands -->
    <section class="container content content-row">
      <div class="brands carouFredSel row">
        <div class="carouFredSel-controls">
          <div class="carouFredSel-buttons"><a id="brands-carousel-prev" class="prev" href="#"></a><a id="brands-carousel-next" class="next" href="#"></a></div>
        </div>
        <div class="brands-carousel">
          <ul class="slides">
            <li><a href="#"><img src="public/frontend/images/brand-themeforest.png" alt=""></a></li>
            <li><a href="#"><img src="public/frontend/images/brand-activeden.png" alt=""></a></li>
            <li><a href="#"><img src="public/frontend/images/brand-audiojungle.png" alt=""></a></li>
            <li><a href="#"><img src="public/frontend/images/brand-videohive.png" alt=""></a></li>
            <li><a href="#"><img src="public/frontend/images/brand-graphicriver.png" alt=""></a></li>
            <li><a href="#"><img src="public/frontend/images/brand-3docean.png" alt=""></a></li>
            <li><a href="#"><img src="public/frontend/images/brand-themeforest.png" alt=""></a></li>
            <li><a href="#"><img src="public/frontend/images/brand-activeden.png" alt=""></a></li>
            <li><a href="#"><img src="public/frontend/images/brand-audiojungle.png" alt=""></a></li>
            <li><a href="#"><img src="public/frontend/images/brand-videohive.png" alt=""></a></li>
            <li><a href="#"><img src="public/frontend/images/brand-graphicriver.png" alt=""></a></li>
            <li><a href="#"><img src="public/frontend/images/brand-3docean.png" alt=""></a></li>
          </ul>
        </div>
      </div>
    </section>
    <!-- //end Brands -->
    <!-- Two columns content -->
    <section class="container content">
      <div class="row">

        <!-- Left column -->
        <aside class="col-sm-4 col-md-3 col-lg-3 content-aside">

          <!-- Shop by categories -->
          <section>
            <h3>DANH MỤC </h3>
            <ul class="expander-list">
              <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">THIẾT BỊ ĐIỆN TỬ</a> </span>
                <ul>
                  <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">ĐIỆN THOẠI DI ĐỘNG</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Iphone</a></span></li>
                      <li><span class="name"><a href="#">Ipad Pro, Ipad New</a></span></li>
                      <li><span class="name"><a href="#">Samsung</a></span></li>
                      <li><span class="name"><a href="#">Sony</a></span></li>
                      <li><span class="name"><a href="#">Khác</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">LAPTOP</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Macbook</a></span></li>
                      <li><span class="name"><a href="#">Chormebook</a></span></li>
                      <li><span class="name"><a href="#">Laptop cơ bản</a></span></li>
                      <li><span class="name"><a href="#">Dòng giải trí</a></span></li>
                      <li><span class="name"><a href="#">Dòng 2-in-1</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">MÁY TÍNH BẢNG</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Apple</a></span></li>
                      <li><span class="name"><a href="#">Samsung</a></span></li>
                      <li><span class="name"><a href="#">Khác</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">MÁY ẢNH &#38; MÁY QUAY PHIM</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Máy ảnh siêu room</a></span></li>
                      <li><span class="name"><a href="#">Máy chụp lấy ngay &#38; Phụ kiện</a></span></li>
                      <li><span class="name"><a href="#">Máy ảnh du lịch</a></span></li>
                      <li><span class="name"><a href="#">Camera giám sát</a></span></li>
                      <li><span class="name"><a href="#">Camera xe hơi</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">THIẾT BỊ ÂM THANH</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Âm thanh sống &#38; Sân khấu</a></span></li>
                      <li><span class="name"><a href="#">Máy ghi âm</a></span></li>
                      <li><span class="name"><a href="#">Loa di động</a></span></li>
                      <li><span class="name"><a href="#">Hệ thống âm thanh ngoài trời</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="View/Layout/device.html">TIVI</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Smart TV</a></span></li>
                      <li><span class="name"><a href="#">Tivi LCD</a></span></li>
                      <li><span class="name"><a href="#">Tivi Plasma</a></span></li>
                      <li><span class="name"><a href="#">Tivi QLED</a></span></li>
                    </ul>
                  </li>
                </ul>
              <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN ĐIỆN TỬ</a> </span>
                <ul>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">LINH KIỆN MÁY TÍNH</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Card màn hình</a></span></li>
                      <li><span class="name"><a href="#">Hệ thống tản nhiệt</a></span></li>
                      <li><span class="name"><a href="#">Ổ đĩa quang</a></span></li>
                      <li><span class="name"><a href="#">RAM máy tính</a></span></li>
                      <li><span class="name"><a href="#">Nguồn máy tính</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Đèn Flash</a></span></li>
                      <li><span class="name"><a href="#">Ông kính</a></span></li>
                      <li><span class="name"><a href="#">Pin</a></span></li>
                      <li><span class="name"><a href="#">Thẻ nhớ</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN DI ĐỘNG</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Pin sạc dự phòng</a></span></li>
                      <li><span class="name"><a href="#">Bộ sạc có dây</a></span></li>
                      <li><span class="name"><a href="#">Sim &#38; Thẻ cào</a></span></li>
                      <li><span class="name"><a href="#">Ốp lưng &#38; Bao da điện thoại</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN MÁY TÍNH</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Chuột</a></span></li>
                      <li><span class="name"><a href="#">Công cụ đồ họa</a></span></li>
                      <li><span class="name"><a href="#">Màn hình máy tính</a></span></li>
                      <li><span class="name"><a href="#">Miếng lót chuột</a></span></li>
                      <li><span class="name"><a href="#">Pin Laptop</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN TIVI</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Kính 3D</a></span></li>
                      <li><span class="name"><a href="#">Điều khiển từ xa</a></span></li>
                      <li><span class="name"><a href="#">Máy chiếu</a></span></li>
                      <li><span class="name"><a href="#">Aten TV</a></span></li>
                      <li><span class="name"><a href="#">Adapter TV</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">THIẾT BỊ LƯU TRỮ</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Ổ cứng SSD gắn ngoài</a></span></li>
                      <li><span class="name"><a href="#">Ổ cứng SSD gắn trong</a></span></li>
                      <li><span class="name"><a href="#">USB</a></span></li>
                    </ul>
                  </li>
                </ul>
              <li> <span class="name"> <span class="expander">-</span> <a href="#">CHĂM SÓC &#38; LÀM ĐẸP</a> </span>
                <ul>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">CHĂM SÓC DA MẶT</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Dưỡng da &#38; Serum</a></span></li>
                      <li><span class="name"><a href="#">Sữa rửa mặt</a></span></li>
                      <li><span class="name"><a href="#">Dưỡng môi</a></span></li>
                      <li><span class="name"><a href="#">Kem chống nắng &#38; Phục hồi</a></span></li>
                      <li><span class="name"><a href="#">Mặt nạ lột &#38; Hạt tẩy tế bào</a></span></li>
                      <li><span class="name"><a href="#">Nước hoa hồng &#38; Xịt khoáng</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">CHĂM SÓC TÓC</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Dầu gội</a></span></li>
                      <li><span class="name"><a href="#">Dầu xả</a></span></li>
                      <li><span class="name"><a href="#">Thuốc nhuộm tóc</a></span></li>
                      <li><span class="name"><a href="#">Phụ kiện cho tóc</a></span></li>
                      <li><span class="name"><a href="#">Tóc giả, tóc nối &#38; Phồng tóc</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">DỤNG CỤ CHĂM SÓC SẮC ĐẸP</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Máy duỗi tóc</a></span></li>
                      <li><span class="name"><a href="#">Máy làm tóc đa năng</a></span></li>
                      <li><span class="name"><a href="#">Máy sấy tóc</a></span></li>
                      <li><span class="name"><a href="#">Máy massage &#38; Làm thon cơ thể</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG ĐIỂM</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Mắt</a></span></li>
                      <li><span class="name"><a href="#">Mặt</a></span></li>
                      <li><span class="name"><a href="#">Môi</a></span></li>
                      <li><span class="name"><a href="#">Móng</a></span></li>
                      <li><span class="name"><a href="#">Tẩy trang</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">THỰC PHẨM BỔ SUNG</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Trà giảm cân</a></span></li>
                      <li><span class="name"><a href="#">Protein</a></span></li>
                      <li><span class="name"><a href="#">Phân giải và đốt cháy mỡ</a></span></li>
                      <li><span class="name"><a href="#">Kiểm soát cân nặng</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">THIẾT BỊ Y TẾ</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Dụng cụ sơ cứu</a></span></li>
                      <li><span class="name"><a href="#">Thiết bị theo dõi sức khỏe</a></span></li>
                      <li><span class="name"><a href="#">Máy xông mũi họng</a></span></li>
                      <li><span class="name"><a href="#">Thuốc mỡ &#38; Kem</a></span></li>
                    </ul>
                  </li>
                </ul>
              <li> <span class="name"> <span class="expander">-</span> <a href="#">THỜI TRANG NỮ</a> </span>
                <ul>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG PHỤC NỮ</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Áo khoác</a></span></li>
                      <li><span class="name"><a href="#">Quần jeans</a></span></li>
                      <li><span class="name"><a href="#">Áo len &#38; Áo tay dài</a></span></li>
                      <li><span class="name"><a href="#">Váy</a></span></li>
                      <li><span class="name"><a href="#">Quần dài &#38; Quần legging</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">TÚI XÁCH NỮ</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Balo</a></span></li>
                      <li><span class="name"><a href="#">Túi đeo chéo &#38; Túi đeo vai</a></span></li>
                      <li><span class="name"><a href="#">Ví &#38; Phụ kiện</a></span></li>
                      <li><span class="name"><a href="#">Túi đeo tay</a></span></li>
                      <li><span class="name"><a href="#">Ví dự tiệc</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">GIÀY NỮ</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Giày cao gót</a></span></li>
                      <li><span class="name"><a href="#">Giày đế bằng</a></span></li>
                      <li><span class="name"><a href="#">Seakers</a></span></li>
                      <li><span class="name"><a href="#">Sadal</a></span></li>
                      <li><span class="name"><a href="#">Dép thời trang</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN NỮ</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Găng tay</a></span></li>
                      <li><span class="name"><a href="#">Khăn choàng</a></span></li>
                      <li><span class="name"><a href="#">Mũ thời trang</a></span></li>
                      <li><span class="name"><a href="#">Thắt lưng</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG PHỤC BÉ GÁI</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Áo bé gái</a></span></li>
                      <li><span class="name"><a href="#">Áo khoác bé gái</a></span></li>
                      <li><span class="name"><a href="#">Đầm bé gái</a></span></li>
                      <li><span class="name"><a href="#">Quần &#38; Váy bé gái</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN BÉ GÁI</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Mũ bé gái</a></span></li>
                      <li><span class="name"><a href="#">Dù &#38; Áo mưa bé gái</a></span></li>
                      <li><span class="name"><a href="#">Găng tay &#38; Khăn bé gái</a></span></li>
                    </ul>
                  </li>
                </ul>
              <li> <span class="name"> <span class="expander">-</span> <a href="#">THỜI TRANG NAM</a> </span>
                <ul>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG PHỤC NAM</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Áo khoác</a></span></li>
                      <li><span class="name"><a href="#">Áo sơ mi</a></span></li>
                      <li><span class="name"><a href="#">Bộ vest</a></span></li>
                      <li><span class="name"><a href="#">Quần dài</a></span></li>
                      <li><span class="name"><a href="#">Quần jeans</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">GIÀY NAM</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Giày công sở</a></span></li>
                      <li><span class="name"><a href="#">Giày lười</a></span></li>
                      <li><span class="name"><a href="#">Sneakers</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">TÚI SÁCH NAM</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Balo</a></span></li>
                      <li><span class="name"><a href="#">Túi laptop đeo vai</a></span></li>
                      <li><span class="name"><a href="#">Cặp công sở</a></span></li>
                      <li><span class="name"><a href="#">Túi đeo chéo</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN NAM</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Cà vạt &#38; Nơ</a></span></li>
                      <li><span class="name"><a href="#">Găng tay</a></span></li>
                      <li><span class="name"><a href="#">Khăn choàng cổ</a></span></li>
                      <li><span class="name"><a href="#">Thắt lưng</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG PHỤC BÉ TRAI</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Áo bé trai</a></span></li>
                      <li><span class="name"><a href="#">Áo khoác bé trai</a></span></li>
                      <li><span class="name"><a href="#">Áo len &#38; Áo khoác len bé trai</a></span></li>
                      <li><span class="name"><a href="#">Quần dài &#38; Quần jeans bé trai</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN BÉ TRAI</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Mũ bé trai</a></span></li>
                      <li><span class="name"><a href="#">Dù &#38; Áo mưa bé trai</a></span></li>
                      <li><span class="name"><a href="#">Găng tay &#38; Khăn bé trai</a></span></li>
                    </ul>
                  </li>
                </ul>
              <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN THỜI TRANG</a> </span>
                <ul>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">ĐỒNG HỒ NAM</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Đồng hồ đi chơi</a></span></li>
                      <li><span class="name"><a href="#">Đồng hồ đi làm</a></span></li>
                      <li><span class="name"><a href="#">Đồng hồ thể thao</a></span></li>
                      <li><span class="name"><a href="#">Đồng hồ thời trang</a></span></li>
                      <li><span class="name"><a href="#">Phụ kiện đồng hồ</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">ĐỒNG HỒ NỮ</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Đồng hồ đi chơi</a></span></li>
                      <li><span class="name"><a href="#">Đồng hồ đi làm</a></span></li>
                      <li><span class="name"><a href="#">Đồng hồ thể thao</a></span></li>
                      <li><span class="name"><a href="#">Đồng hồ thời trang</a></span></li>
                      <li><span class="name"><a href="#">Phụ kiện đồng hồ</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">KÍNH THỜI TRANG</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Kính thời trang nữ</a></span></li>
                      <li><span class="name"><a href="#">Kính thời trang nam</a></span></li>
                      <li><span class="name"><a href="#">Kính thời trang trẻ em</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">KÍNH ÁP TRÒNG</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Kính áp tròng không màu</a></span></li>
                      <li><span class="name"><a href="#">Kính áp tròng màu</a></span></li>
                      <li><span class="name"><a href="#">Thuốc nhỏ mắt</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG SỨC NỮ</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Trang sức cao cấp</a></span></li>
                      <li><span class="name"><a href="#">Trang sức thời trang</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">TRANG SỨC NAM</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Trang sức cao cấp</a></span></li>
                      <li><span class="name"><a href="#">Trang sức thời trang</a></span></li>
                    </ul>
                  </li>
                </ul>
              <li> <span class="name"> <span class="expander">-</span> <a href="#">THỂ THAO &#38; DU LỊCH</a> </span>
                <ul>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">VALI &#38; TÚI DU LỊCH </a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Balo &#38; Túi laptop</a></span></li>
                      <li><span class="name"><a href="#">Túi du lịch</a></span></li>
                      <li><span class="name"><a href="#">Vali du lịch</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">HOẠT ĐỘNG DÃ NGOẠI</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Câu cá</a></span></li>
                      <li><span class="name"><a href="#">Golf</a></span></li>
                      <li><span class="name"><a href="#">Leo núi</a></span></li>
                      <li><span class="name"><a href="#">Trượt patin</a></span></li>
                      <li><span class="name"><a href="#">Xe scooter</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">PHỤ KIỆN </a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Dây đai &#38; Phụ kiện</a></span></li>
                      <li><span class="name"><a href="#">Bình nước thể thao</a></span></li>
                      <li><span class="name"><a href="#">Phụ kiện đạp xe</a></span></li>
                      <li><span class="name"><a href="#">Nẹp &#38; Hỗ trợ</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">THỂ DỤC, THỂ HÌNH</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Chạy bộ</a></span></li>
                      <li><span class="name"><a href="#">Máy tập thể hình</a></span></li>
                      <li><span class="name"><a href="#">Tạ</a></span></li>
                      <li><span class="name"><a href="#">Yoga</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">ĐẤM BỐC, VÕ THUẬT</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Đồng phục đấm bốc</a></span></li>
                      <li><span class="name"><a href="#">Găng tay đấm bốc</a></span></li>
                      <li><span class="name"><a href="#">Tấm lót đấm bốc</a></span></li>
                      <li><span class="name"><a href="#">Bao cát &#38; Phụ kiện</a></span></li>
                    </ul>
                  </li>
                  <li> <span class="name"> <span class="expander">-</span> <a href="#">CÁC MÔN THỂ THAO ĐỒNG ĐỘI</a> </span>
                    <ul>
                      <li><span class="name"><a href="#">Bóng chày</a></span></li>
                      <li><span class="name"><a href="#">Bóng chuyền</a></span></li>
                      <li><span class="name"><a href="#">Bóng đá</a></span></li>
                      <li><span class="name"><a href="#">Bóng rổ</a></span></li>
                      <li><span class="name"><a href="#">Cầu lông</a></span></li>
                    </ul>
                  </li>
                </ul>
          </section>
          <!-- //end Shop by categories -->

          <div class="section-divider"></div>

          <!-- BEST SELLERS -->
          <h3><a href="#">BÁN CHẠY</a></h3>
          <div class="products-widget jcarousel-skin-previews vertical">
            <ul class="slides">
              <li>
                <div class="product"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-07-small.jpg" alt=""></a>
                  <p class="name"><a href="View/Layout/product_default.phtml" class="preview-image">Kem</a></p>
                  <span class="rating"> </span> <span class="price">$44.95</span> </div>
              </li>
              <li>
                <div class="product"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-08-small.jpg" alt=""></a>
                  <p class="name"><a href="View/Layout/product_default.phtml" class="preview-image">Kem</a></p>
                  <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="price">$44.95</span> </div>
              </li>
              <li>
                <div class="product"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-09-small.jpg" alt=""></a>
                  <p class="name"><a href="View/Layout/product_default.phtml" class="preview-image">Kem</a></p>
                  <span class="rating"> </span> <span class="price">$22.95</span> </div>
              </li>
              <li>
                <div class="product"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-07-small.jpg" alt=""></a>
                  <p class="name"><a href="View/Layout/product_default.phtml" class="preview-image">Kem</a></p>
                  <span class="rating"> </span> <span class="price">$44.95</span> </div>
              </li>
              <li>
                <div class="product"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-08-small.jpg" alt=""></a>
                  <p class="name"><a href="View/Layout/product_default.phtml" class="preview-image">Kem</a></p>
                  <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="price">$44.95</span> </div>
              </li>
              <li>
                <div class="product"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-09-small.jpg" alt=""></a>
                  <p class="name"><a href="View/Layout/product_default.phtml" class="preview-image">Kem</a></p>
                  <span class="rating"> </span> <span class="price">$22.95</span> </div>
              </li>
            </ul>
          </div>
          <!-- //end Best Sellers -->
          <div class="section-divider"></div>
          <!-- Blog Widget Small -->

          <!-- //end Blog Widjet Small -->

        </aside>
        <!-- //end Left column -->

        <!-- Right column -->
        <section class="col-sm-8 col-md-9 col-lg-9 content-center">
          <!-- Featured Products -->
          <section>
            <h3>SẢN PHẨM NỔI BẬT</h3>

            <!-- Products list -->
            <div class="row products-list">
              <div class="product-preview">
                <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-03.jpg" width="270" height="328" alt=""></a>
                  <ul class="product-controls-list right">
                    <li><span class="label label-sale">SALE</span></li>
                    <li><span class="label">-20%</span></li>
                  </ul>
                  <ul class="product-controls-list right hide-right">
                    <li class="top-out"></li>
                    <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                    <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                    <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                  </ul>
                  <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY </a>
                  <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                </div>
                <h3 class="title"><a href="View/Layout/product_default.phtml">Kem</a></h3>
                <span class="price old">$54.22</span> <span class="price new">$44.95</span> </div>
              <div class="product-preview ">
                <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-04.jpg" width="270" height="328" alt=""></a>
                  <ul class="product-controls-list">
                    <li><span class="label label-new">NEW</span></li>
                  </ul>
                  <ul class="product-controls-list right hide-right">
                    <li class="top-out"></li>
                    <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                    <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                    <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                  </ul>
                  <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY </a>
                  <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                </div>
                <h3 class="title"><a href="View/Layout/product_default.phtml">Kem</a></h3>
                <span class="price">$44.95</span> </div>
              <div class="product-preview ">
                <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-05.jpg" width="270" height="328" alt=""></a>
                  <ul class="product-controls-list right">
                    <li><span class="label label-sale">SALE</span></li>
                    <li><span class="label">-20%</span></li>
                  </ul>
                  <ul class="product-controls-list right hide-right">
                    <li class="top-out"></li>
                    <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                    <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                    <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                  </ul>
                  <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY </a>
                  <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                </div>
                <h3 class="title"><a href="View/Layout/product_default.phtml">Kem</a></h3>
                <span class="price">$44.95</span> </div>
              <div class="product-preview">
                <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-20.jpg" width="270" height="328" alt=""></a>
                  <ul class="product-controls-list right hide-right">
                    <li class="top-out"></li>
                    <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                    <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                    <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                  </ul>
                  <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY </a>
                  <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                </div>
                <h3 class="title"><a href="View/Layout/product_default.phtml"></a>Kem</h3>
                <div class="product-options-outer">
                  <div class="product-options"> <i class="icon icon-color icon-color-white" data-href="public/frontend/images/products/product-12.jpg"></i> <i class="icon icon-color icon-color-beige" data-href="public/frontend/images/products/product-17.jpg"></i> <i class="icon icon-color icon-color-red" data-href="public/frontend/images/products/product-25.jpg"></i> <i class="icon icon-color icon-color-pink" data-href="public/frontend/images/products/product-31.jpg"></i> <i class="icon icon-color icon-color-magneta"  data-href="public/frontend/images/products/product-07.jpg"></i> <i class="disable icon icon-color icon-color-green"  data-href="public/frontend/images/products/product-11.jpg"></i> <i class="disable icon icon-color icon-color-gray"></i> <i class="disable icon icon-color icon-color-brown"></i> </div>
                </div>
                <span class="price">$44.95</span> </div>
              <div class="product-preview">
                <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-22.jpg" width="269" height="328" alt=""></a>
                  <ul class="product-controls-list right hide-right">
                    <li class="top-out"></li>
                    <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                    <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                    <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                  </ul>
                  <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY </a>
                  <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                </div>
                <h3 class="title"><a href="View/Layout/product_default.phtml">Kem</a></h3>
                <div class="product-options-outer">
                  <div class="product-options"> <i class="disable icon icon-size">39</i> <i class="icon icon-size">40</i> <i class="disable icon icon-size">41</i> <i class="icon icon-size">42</i> <i class="icon icon-size">43</i> <i class="icon icon-size">44</i> <i class="icon icon-size">45</i> <i class="disable icon icon-size">46</i> </div>
                  <div class="product-options"> <i class="icon icon-color icon-color-white" data-href="public/frontend/images/products/product-12.jpg"></i> <i class="icon icon-color icon-color-beige" data-href="public/frontend/images/products/product-17.jpg"></i> <i class="icon icon-color icon-color-red" data-href="public/frontend/images/products/product-25.jpg"></i> <i class="icon icon-color icon-color-pink" data-href="public/frontend/images/products/product-31.jpg"></i> <i class="icon icon-color icon-color-magneta"  data-href="public/frontend/images/products/product-07.jpg"></i> <i class="disable icon icon-color icon-color-green"  data-href="public/frontend/images/products/product-11.jpg"></i> <i class="disable icon icon-color icon-color-gray"></i> <i class="disable icon icon-color icon-color-brown"></i> </div>
                </div>
                <span class="price">$74.95</span> </div>
              <div class="product-preview ">
                <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-06.jpg" width="270" height="328" alt=""></a>
                  <ul class="product-controls-list">
                    <li><span class="label label-new">NEW</span></li>
                  </ul>
                  <ul class="product-controls-list right hide-right">
                    <li class="top-out"></li>
                    <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                    <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                    <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                  </ul>
                  <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY </a>
                  <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                </div>
                <h3 class="title"><a href="View/Layout/product_default.phtml">Kem</a></h3>
                <span class="price">$44.95</span> </div>
            </div>
            <!-- //end Products list -->

            <!-- Product view compact -->
            <div class="product-view-ajax">
              <div class="ajax-loader progress progress-striped active">
                <div class="progress-bar progress-bar-danger" role="progressbar"></div>
              </div>
              <div class="layar"></div>
              <div class="product-view-container"> </div>
            </div>
            <!-- //end Product view compact -->
          </section>
          <div class="section-divider"></div>
          <!-- On Sale Products -->
          <section>
            <h3>ĐANG GIẢM GIÁ</h3>

            <!-- Products list -->
            <div class="row">
              <div class="product-carousel">
                <div class="item">
                  <div class="product-preview">
                    <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-23.jpg" width="270" height="328" alt=""></a>
                      <ul class="product-controls-list right">
                        <li><span class="label label-sale">SALE</span></li>
                        <li><span class="label">-20%</span></li>
                      </ul>
                      <ul class="product-controls-list right hide-right">
                        <li class="top-out"></li>
                        <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                        <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                        <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                      </ul>
                      <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY</a>
                      <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                    </div>
                    <h3 class="title"><a href="#">Kem</a></h3>
                    <span class="price old">$54.22</span> <span class="price new">$44.95</span> </div>
                </div>
                <div class="item">
                  <div class="product-preview">
                    <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-25.jpg" width="270" height="328" alt=""></a>
                      <ul class="product-controls-list right">
                        <li><span class="label label-sale">SALE</span></li>
                        <li><span class="label">-20%</span></li>
                      </ul>
                      <ul class="product-controls-list right hide-right">
                        <li class="top-out"></li>
                        <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                        <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                        <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                      </ul>
                      <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY </a>
                      <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                    </div>
                    <h3 class="title"><a href="#">Kem</a></h3>
                    <span class="price old">$54.22</span> <span class="price new">$44.95</span> </div>
                </div>
                <div class="item">
                  <div class="product-preview">
                    <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-05.jpg" width="270" height="328" alt=""></a>
                      <ul class="product-controls-list right">
                        <li><span class="label label-sale">SALE</span></li>
                        <li><span class="label">-20%</span></li>
                      </ul>
                      <ul class="product-controls-list right hide-right">
                        <li class="top-out"></li>
                        <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                        <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                        <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                      </ul>
                      <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY</a>
                      <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                    </div>
                    <h3 class="title"><a href="#">Kem</a></h3>
                    <span class="price old">$54.22</span> <span class="price new">$44.95</span> </div>
                </div>
                <div class="item">
                  <div class="product-preview">
                    <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-06.jpg" width="270" height="328" alt=""></a>
                      <ul class="product-controls-list right">
                        <li><span class="label label-sale">SALE</span></li>
                        <li><span class="label">-20%</span></li>
                      </ul>
                      <ul class="product-controls-list right hide-right">
                        <li class="top-out"></li>
                        <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                        <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                        <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                      </ul>
                      <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY </a>
                      <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                    </div>
                    <h3 class="title"><a href="#">Kem</a></h3>
                    <span class="price old">$54.22</span> <span class="price new">$44.95</span> </div>
                </div>
                <div class="item">
                  <div class="product-preview">
                    <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-03.jpg" width="270" height="328" alt=""></a>
                      <ul class="product-controls-list right">
                        <li><span class="label label-sale">SALE</span></li>
                        <li><span class="label">-20%</span></li>
                      </ul>
                      <ul class="product-controls-list right hide-right">
                        <li class="top-out"></li>
                        <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                        <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                        <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                      </ul>
                      <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY </a>
                      <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                    </div>
                    <h3 class="title"><a href="#">Kem</a></h3>
                    <span class="price old">$54.22</span> <span class="price new">$44.95</span> </div>
                </div>
                <div class="item">
                  <div class="product-preview">
                    <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-04.jpg" width="270" height="328" alt=""></a>
                      <ul class="product-controls-list right">
                        <li><span class="label label-sale">SALE</span></li>
                        <li><span class="label">-20%</span></li>
                      </ul>
                      <ul class="product-controls-list right hide-right">
                        <li class="top-out"></li>
                        <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                        <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                        <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                      </ul>
                      <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY</a>
                      <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                    </div>
                    <h3 class="title"><a href="#">Kem</a></h3>
                    <span class="price old">$54.22</span> <span class="price new">$44.95</span> </div>
                </div>
                <div class="item">
                  <div class="product-preview">
                    <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-05.jpg" width="270" height="328" alt=""></a>
                      <ul class="product-controls-list right">
                        <li><span class="label label-sale">SALE</span></li>
                        <li><span class="label">-20%</span></li>
                      </ul>
                      <ul class="product-controls-list right hide-right">
                        <li class="top-out"></li>
                        <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                        <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                        <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                      </ul>
                      <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY </a>
                      <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                    </div>
                    <h3 class="title"><a href="#">Kem</a></h3>
                    <span class="price old">$54.22</span> <span class="price new">$44.95</span> </div>
                </div>
                <div class="item">
                  <div class="product-preview">
                    <div class="preview animate scale"> <a href="View/Layout/product_default.phtml" class="preview-image"><img class="img-responsive animate scale" src="public/frontend/images/products/product-06.jpg" width="270" height="328" alt=""></a>
                      <ul class="product-controls-list right">
                        <li><span class="label label-sale">SALE</span></li>
                        <li><span class="label">-20%</span></li>
                      </ul>
                      <ul class="product-controls-list right hide-right">
                        <li class="top-out"></li>
                        <li><a href="#" class="circle"><span class="icon-heart"></span></a></li>
                        <li><a href="#" class="circle"><span class="icon-justice"></span></a></li>
                        <li><a href="#" class="cart"><span class="icon-basket"></span></a></li>
                      </ul>
                      <a href="_ajax_view-product.html" class="quick-view hidden-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span> <span class="icon-zoom-in-2"></span> MUA NGAY </a>
                      <div class="quick-view visible-xs"> <span class="rating"> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-3"></i> <i class="icon-star-empty"></i> </span></div>
                    </div>
                    <h3 class="title"><a href="#">Kem</a></h3>
                    <span class="price old">$54.22</span> <span class="price new">$44.95</span> </div>
                </div>
              </div>
              <!-- product view ajax container -->
              <div class="product-view-ajax-container"> </div>
              <!-- //end product view ajax container -->
            </div>
            <!-- //end Products list -->

          </section>

          <!-- //end On Sale Products -->

        </section>
        <!-- //end Right column -->

      </div>
    </section>
    <!-- //end Two columns content --> <!-- Social navbar -->
    <section class="content content-border nopad-xs social-widget">
      <div class="container">
        <div class="row">
          <div class="col-sm-6 col-md-6  col-lg-6 newsletter collapsed-block">
            <div class="row">
              <div class="col-lg-5  col-md-12 col-sm-12 ">
                <h3>GIẤY CHỨNG NHẬN <a class="expander visible-xs" href="#TabBlock-1">+</a></h3>
              </div>
              <div class="col-sm-12 col-md-12 col-lg-6 tabBlock" id="TabBlock-1">
                <h3>ĐĂNG KÍ NHẬN TIN</h3>
                <form class="form-inline" role="form">
                  <div class="form-group input-control">
                    <button type="submit" class="button"><span class="icon-envelop"></span></button>
                    <input type="text" class="form-control" value="Your E-mail..." onblur="if (this.value == '') {this.value = 'Your E-mail...';}" onfocus="if(this.value == 'Your E-mail...') {this.value = '';}">
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-6 col-lg-6 collapsed-block">
            <h3>KÊT NỐI VỚI CHÚNG TÔI<a class="expander visible-xs" href="#TabBlock-2">+</a></h3>
            <div  class="tabBlock" id="TabBlock-2">
              <ul class="find-us">
                <li class="divider"><a href="#" class="animate-scale"><span class="icon icon-facebook-3"></span></a></li>
                <li class="divider"><a href="#" class="animate-scale"><span class="icon icon-twitter-3"></span></a></li>
                <li class="divider"><a href="#" class="animate-scale"><span class="icon icon-linkedin-2"></span></a></li>
                <li class="divider"><a href="#" class="animate-scale"><span class="icon icon-youtube-3"></span></a></li>
                <li class="divider"><a href="#" class="animate-scale"><span class="icon icon-pinterest-2"></span></a></li>
                <li class="divider"><a href="#" class="animate-scale"><span class="icon icon-googleplus-2"></span></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- //end Social navbar -->

    <!-- Footer -->
    <footer>
      <section class="footer-navbar dark">
        <div class="container content nopad-xs">
          <div class="row">
            <div class="col-sm-6 col-md-3 col-lg-3 collapsed-block">
              <h3>THÔNG TIN<a class="expander visible-xs" href="#TabBlock-3">+</a></h3>
              <div  class="tabBlock" id="TabBlock-3">
                <ul class="menu">
                  <li><a href="about.html">Về chúng tôi</a></li>
                  <li><a href="#">Vận chuyển &amp; Trả hàng</a></li>
                  <li><a href="#">Bảo mật</a></li>
                  <li><a href="#">Điều kiện sử dụng</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-6 col-md-3 col-lg-3 collapsed-block"> <h3><span class="attention"><span class="attention_icon"></span></span>DỊCH VỤ KHÁCH HÀNG<a class="expander visible-xs" href="#TabBlock-4">+</a></h3>
              <div  class="tabBlock" id="TabBlock-4">
                <ul class="menu">
                  <li><a href="#">Hỗ trợ trực tuyến</a></li>
                  <li><a href="#">Trợ giúp &amp; Câu hỏi thường gặp</a></li>
                  <li><a href="#">Cuộc gọi trung tâm</a></li>
                </ul>
              </div>
            </div>
            <div class="clearfix visible-sm"></div>
            <div class="col-sm-6 col-md-3 col-lg-3 collapsed-block">
              <h3>TÀI KHOẢN CỦA TÔI<a class="expander visible-xs" href="#TabBlock-5">+</a></h3>
              <div  class="tabBlock" id="TabBlock-5">
                <ul class="menu">
                  <li><a href="View/Layout/login.phtml">Tài khoản của tôi</a></li>
                  <li><a href="View/Layout/login.phtml">Lịch sử đơn hàng</a></li>
                  <li><a href="View/Layout/login.phtml">Tìm kiếm nâng cao</a></li>
                  <li><a href="View/Layout/login.phtml">Đánh giá</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-6 col-md-3 col-lg-3 collapsed-block">
              <h3>LIÊN HỆ VỚI CHÚNG TÔI<a class="expander visible-xs" href="#TabBlock-6">+</a></h3>
              <div  class="tabBlock" id="TabBlock-6">
                <ul class="menu">
                  <li><span class="icon icon-house"></span> PTIT</li>
                  <li><span class="icon icon-phone-4"></span> 0123456789</li>
                  <li><span class="icon icon-envelop"></span> <a href="http://khungbois.xyz">khungbois.xyz</a></li>
                  <li><span class="icon icon-facebook-3"></span> <a href="#">Trịnh Ngọc Ánh</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section class="footer-bottom-block container">
        <div class="row">
          <div class="col-sm-5 col-md-4 copyright-text"> &copy; 2018<a href="#">Megatron</a>. All Rights Reserved. </div>
          <div class="col-sm-3 col-md-4">
            <ul class="payment-list pull-right">
              <li><img src="public/frontend/images/icon-payment-01.png" width="36" height="22" alt=""></li>
              <li><img src="public/frontend/images/icon-payment-02.png" width="36" height="22" alt=""></li>
              <li><img src="public/frontend/images/icon-payment-03.png" width="36" height="22" alt=""></li>
              <li><img src="public/frontend/images/icon-payment-04.png" width="36" height="22" alt=""></li>
              <li><img src="public/frontend/images/icon-payment-05.png" width="36" height="22" alt=""></li>
            </ul>
          </div>
        </div>
      </section>
    </footer>
    <div id="outer-overlay"></div>
  </div>
</div>

<!-- Popup box -->

<div id="popup-box">
  <div class="col-sm-6 col-md-5 col-lg-5"><img src="public/frontend/images/products/product-02.jpg" class="img-responsive animate scale" alt="">
    <div class="clearfix"></div>
    <label class="checkbox-inline">
      <input type="checkbox" id="inlineCheckbox1" value="option1">
      Không hiện lại hộp thoại </label>
  </div>
  <div class="col-sm-6 col-md-7 col-lg-7">
    <h1>ĐANG GIẢM GIÁ 25% TẤT CẢ CÁC MẶT HÀNG ĐIỆN TỬ</h1>
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec eros tellus, scelerisque nec, rhoncus eget, laoreet sit amet, nunc. Ut sit amet turpis. In est arcu, sollicitudin eu, vehicula venenatis, tempor vitae, est.

      Maecenas eu enim in lorem scelerisque auctor. Ut non erat. Suspendisse fermentum posuere lectus. </p>
    <form role="form">
      <div class="form-group input-control">
        <button type="submit" class="button"><span class="icon-envelop"></span></button>
        <input type="text" class="form-control" value="Your E-mail..." onblur="if (this.value == '') {this.value = 'Your E-mail...';}" onfocus="if(this.value == 'Your E-mail...') {this.value = '';}">
      </div>
    </form>
  </div>
</div>
<!-- //end Popup box -->
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="public/frontend/js/html5shiv.js"></script>
<script src="public/frontend/js/respond.min.js"></script>
<![endif]-->

<script src="public/frontend/js/jquery-1.10.2.min.js"></script>
<script src="public/frontend/js/jquery.easing.1.3.js"></script>
<script src="public/frontend/js/jquery-ui-1.10.3.custom.min.js"></script>
<script src="public/frontend/js/jquery.ui.touch-punch.min.js"></script>
<script src="public/frontend/js/jquery.mousewheel.min.js"></script>
<script src="public/frontend/js/bootstrap.min.js"></script>
<script src="public/frontend/js/jquery.flexslider.js"></script>
<script src="public/frontend/js/owl.carousel.js"></script>
<script src="public/frontend/js/jquery.jcarousel.min.js"></script>
<script src="public/frontend/js/cloudzoom.js"></script>
<script src="public/frontend/js/jquery.isotope.min.js"></script>
<script src="public/frontend/js/jquery.parallax.js"></script>
<script src="public/frontend/js/jquery.fancybox.js?v=2.1.5"></script>
<script src="public/frontend/js/jquery.inview.js"></script>
<script src="public/frontend/js/hoverIntent.js"></script>
<script src="public/frontend/js/superfish.js"></script>
<script src="public/frontend/js/supersubs.js"></script>
<script src="public/frontend/js/jquery.plugin.js"></script>
<script src="public/frontend/js/jquery.countdown.js"></script>
<script src="public/frontend/js/jquery.carouFredSel-6.2.1-packed.js"></script>
<script src="public/frontend/js/megatron.js"></script>
<!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
<script type="text/javascript" src="public/frontend/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
<script type="text/javascript" src="public/frontend/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('.tp-banner').show().revolution(
            {
                dottedOverlay:"none",
                delay:16000,
                startwidth:1170,
                startheight:795,
                hideThumbs:200,

                thumbWidth:100,
                thumbHeight:50,
                thumbAmount:5,

                navigationType:"none",
                navigationArrows:"solo",
                navigationStyle:"none",

                touchenabled:"on",
                onHoverStop:"on",

                swipe_velocity: 0.7,
                swipe_min_touches: 1,
                swipe_max_touches: 1,
                drag_block_vertical: false,

                parallax:"mouse",
                parallaxBgFreeze:"on",
                parallaxLevels:[7,4,3,2,5,4,3,2,1,0],

                keyboardNavigation:"off",

                navigationHAlign:"center",
                navigationVAlign:"bottom",
                navigationHOffset:0,
                navigationVOffset:20,

                soloArrowLeftHalign:"left",
                soloArrowLeftValign:"center",
                soloArrowLeftHOffset:20,
                soloArrowLeftVOffset:0,

                soloArrowRightHalign:"right",
                soloArrowRightValign:"center",
                soloArrowRightHOffset:20,
                soloArrowRightVOffset:0,

                shadow:0,
                fullWidth:"off",
                fullScreen:"on",

                spinner:"off",

                stopLoop:"off",
                stopAfterLoops:-1,
                stopAtSlide:-1,

                shuffle:"off",

                autoHeight:"off",
                forceFullWidth:"off",



                hideThumbsOnMobile:"off",
                hideNavDelayOnMobile:1500,
                hideBulletsOnMobile:"off",
                hideArrowsOnMobile:"off",
                hideThumbsUnderResolution:0,
                hideTimerBar:"on",
                hideSliderAtLimit:0,
                hideCaptionAtLimit:0,
                hideAllCaptionAtLilmit:0,
                startWithSlide:0,
                fullScreenOffsetContainer: ".navbar"
            });
    }); //ready
</script>
</body>
</html>
